// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwPkfzWXfVg4RtvBV1P4uSIIukQrVt5pM',
    appId: '1:448208010165:web:12983cc7a8d7aea7ec77fc',
    messagingSenderId: '448208010165',
    projectId: 'ahime-134d2',
    authDomain: 'ahime-134d2.firebaseapp.com',
    storageBucket: 'ahime-134d2.appspot.com',
    measurementId: 'G-ZE87XNJMRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_2Ax2GitLD8ATrwrescz-WchfghzFD4',
    appId: '1:448208010165:android:d729f5f66dcccc0cec77fc',
    messagingSenderId: '448208010165',
    projectId: 'ahime-134d2',
    storageBucket: 'ahime-134d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2bL9RRZGKnMFur9nA3O0nvn0PEP2Nrc',
    appId: '1:448208010165:ios:7d3ecc8da60b57d9ec77fc',
    messagingSenderId: '448208010165',
    projectId: 'ahime-134d2',
    storageBucket: 'ahime-134d2.appspot.com',
    iosBundleId: 'com.example.allogroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2bL9RRZGKnMFur9nA3O0nvn0PEP2Nrc',
    appId: '1:448208010165:ios:4b6d4319bcfba1c0ec77fc',
    messagingSenderId: '448208010165',
    projectId: 'ahime-134d2',
    storageBucket: 'ahime-134d2.appspot.com',
    iosBundleId: 'com.example.allogroup.RunnerTests',
  );
}
